scraper:
  timeout: 1 # Seconds before fetching next week's schedule
  course: "Licenciatura em Marketing"
  year: 2
  week:
    start: "2026-09-14"
    end: "2026-12-19"
  #classes:
    #- "Sistemas e Arquiteturas de Computadores"
    #- "Ferramentas de Computação de Elevado Desempenho"

export:
  json:
    file_name: "out.json"
    indent: True

  ics:
    file_name: "out.ics"